# -*- coding: utf-8 -*-
"""TASK_FILE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6G0iWkkqfTS-BmLSPSgrA1NQTUb4ooj
"""

import csv
from collections import defaultdict
from datetime import datetime

def read_orders(filename):
    orders = []
    with open('/content/orders1.csv', 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            orders.append(row)
    return orders

def compute_monthly_revenue(orders):
    monthly_revenue = defaultdict(float)
    for order in orders:
        order_date = datetime.strptime(order['order_date'], '%m-%d-%Y' if '-' in order['order_date'] else '%m/%d/%Y')
        month = order_date.strftime('%Y-%m')
        total_price = float(order['product_price']) * int(order['quantity'])
        monthly_revenue[month] += total_price
    return monthly_revenue

def compute_product_revenue(orders):
    product_revenue = defaultdict(float)
    for order in orders:
        total_price = float(order['product_price']) * int(order['quantity'])
        product_revenue[order['product_name']] += total_price
    return product_revenue

def compute_customer_revenue(orders):
    customer_revenue = defaultdict(float)
    for order in orders:
        total_price = float(order['product_price']) * int(order['quantity'])
        customer_revenue[order['customer_id']] += total_price
    return customer_revenue

def identify_top_customers(customer_revenue):
    sorted_customers = sorted(customer_revenue.items(), key=lambda x: x[1], reverse=True)
    top_customers = sorted_customers[:10]
    return top_customers

if __name__ == "__main__":
    orders = read_orders('orders.csv')

    monthly_revenue = compute_monthly_revenue(orders)
    print("Monthly Revenue:")
    for month, revenue in monthly_revenue.items():
        print(f"{month}: ${revenue:.2f}")

    product_revenue = compute_product_revenue(orders)
    print("\nProduct Revenue:")
    for product, revenue in product_revenue.items():
        print(f"{product}: ${revenue:.2f}")

    customer_revenue = compute_customer_revenue(orders)
    print("\nCustomer Revenue:")
    for customer, revenue in customer_revenue.items():
        print(f"Customer {customer}: ${revenue:.2f}")

    top_customers = identify_top_customers(customer_revenue)
    print("\nTop 10 Customers by Revenue:")
    for customer, revenue in top_customers:
        print(f"Customer {customer}: ${revenue:.2f}")

