# -*- coding: utf-8 -*-
"""TEST_FILE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvdZbLD7KrfQU4RJeWva1o_yRqF_uJAA
"""

import unittest

class TestOrderAnalysis(unittest.TestCase):
    def setUp(self):
        self.orders = [
            {'order_id': '88525', 'customer_id': '2', 'order_date': '5/28/2012', 'product_id': '60101', 'product_name': 'Avery 49', 'product_price': '2.88', 'quantity': '2'},

        ]

    def test_compute_monthly_revenue(self):
        monthly_revenue = compute_monthly_revenue(self.orders)


    def test_compute_product_revenue(self):
        product_revenue = compute_product_revenue(self.orders)


    def test_compute_customer_revenue(self):
        customer_revenue = compute_customer_revenue(self.orders)


    def test_identify_top_customers(self):
        customer_revenue = compute_customer_revenue(self.orders)
        top_customers = identify_top_customers(customer_revenue)


if __name__ == "__main__":
    unittest.main()

